### ISSUE TITLE
Why Contrl-q does not work?

### ISSUE THREAD

**Issue by snowman** [ccheever/nesh-doc#1]
$ nesh

Node v8.11.3
Type .help for more information
nesh> 

Type `console`
nesh> console

Hit the `ctrl-q`
nesh> onsol

Hit the `ctrl-q` again
nesh> nso

Hit the `ctrl-q` again again
nesh> s

Hit the `ctrl-q` again and again
nesh>

**Comment by snowman** [comment]
I have to use `.doc OBJECT` instead, but how could i get the effect of hitting `twice ctrl-q`, so how to fix it? thanks for great job~

**Comment by ccheever** [comment]
i'm not sure how this popped up -- there haven't been any changes recently, but it certainly looks like a bug.

i'll take a look when i have a chance. sorry this isn't working properly
